import random

from faker import Faker
from faker.providers import BaseProvider


class OntologyProvider(BaseProvider):
    def actor(self):
        actors = [
            "Tom Hanks",
            "Arnold Schwarzenegger",
            "Bruce Willis",
            "Sylvester Stallone",
            "Brad Pitt",
            "Tom Cruise",
            "Jason Statham",
            "Hugh Jackman",
            "Robert Downey Jr",
            "Clint Eastwood",
            "Woody Harrelson",
            "Owen Wilson",
            "Mel Gibson",
            "Hugh Grant",
            "Colin Firth",
            "Ben Kingsley",
            "Tom Hiddleston",
            "Jake Gyllenhaal",
            "Chris Hemsworth",
            "Gary Oldman",
            "Johnny Depp",
            "Chris Evans",
            "Daniel Craig",
            "Pierce Brosnan",
            "Will Smith",
            "Alec Baldwin",
            "Jackie Chan",
            "Cillian Murphy",
            "Patrick Dempsey",
            "Colin Farrell",
            "George Clooney",
            "Matthew McConaughey",
            "Ben Affleck",
            "Liam Neeson",
            "Kurt Russell",
            "Daniel Radcliffe",
            "Keanu Reeves",
            "Tim Allen",
            "Rupert Grint",
            "Adam Sandler",
            "Al Pacino",
            "Alan Rickman",
            "Tommy Lee Jones",
            "Morgan Freeman",
            "Danny De Vito",
            "Josh Duhamel",
            "Patrick Swayze",
            "Ryan Gosling",
            "Ashton Kutcher",
            "Antonio Banderas",
            "Eddie Murphy",
            "Bill Murray",
            "Anthony Hopkins",
            "Gaspard Ulliel",
            "Steve Martin",
            "Samuel L. Jackson",
            "Leonardo Di Caprio",
            "Dwayne Johnson",
            "Vin Diesel",
            "Paul Walker",
            "Heath Ledger",
            "Michael J. Fox",
            "Jet Li",
            "Sean Connery",
            "Michael Douglas",
            "Harrison Ford",
            "Denzel Washington",
            "Robin Williams",
            "Gerard Butler",
            "Jack Nicholson",
            "Andy Garcia",
            "Robert De Niro",
            "Dustin Hoffman",
            "Daniel Day Lewis",
            "Ewan McGregor",
            "John Krasinski",
            "Michael Caine",
            "Sean Penn",
            "Robert Duvall",
            "Philip Seymour Hoffman",
            "Benicio Del Torro",
            "Russell Crowe",
            "Kevin Spacey",
            "Christopher Walken",
            "Joe Pesci",
            "Ian McKellen",
            "Jeremy Irons",
            "Javier Bardem",
            "Ralph Fiennes",
            "Jamie Foxx",
            "Joaquin Phoenix",
            "Christian Bale",
            "Edward Norton",
            "Richard Gere",
            "Matt Damon",
            "Robert Redford",
            "Jim Carrey",
            "Don Cheadle",
            "Nicolas Cage",
            "Clive Owen",
            "John Travolta",
            "Mark Wahlberg",
            "James Franco",
            "Josh Hutcherson",
            "Elijah Wood",
            "Orlando Bloom",
            "Viggo Mortensen",
            "John Cusack",
            "Forest Whitaker",
            "Ben Stiller",
            "Steven Seagal",
            "Wesley Snipes",
            "Shia Labeouf",
            "Danny Glover",
            "John Malkovich",
            "Matthew Broderick",
            "Cuba Gooding Jr.",
            "Justin Timberlake",
            "Harvey Keitel",
            "Eugenio Derbez",
            "Chiwetel Ejiofor",
            "Bradley Cooper",
            "Eric Bana",
            "James Marsden",
            "Tom Selleck",
            "Jean Claude Van Damme",
            "Jude Law",
            "Jack Black",
            "Chuck Norris",
            "Idris Elba",
            "James McAvoy",
            "Robert Pattinson",
            "Kiefer Sutherland",
            "William Levy",
            "Kit Harington",
            "Kevin Costner",
            "Chris Pine",
            "Tom Hardy",
            "Alan Cumming",
            "Stanley Tucci",
            "Donald Sutherland",
            "Brendan Fraser",
            "Jason Isaacs",
            "Kevin Bacon",
            "Liev Schreiber",
            "Mark Ruffalo",
            "Paul Rudd",
            "Rowan Atkinson",
            "Stellan Skarsgård",
            "Steve Carell",
        ]

        return random.choice(actors)

    def actress(self):
        actresses = [
            "Jennifer Aniston",
            "Sandra Bullock",
            "Nicole Kidman",
            "Julia Roberts",
            "Angelina Jolie",
            "Marion Cotillard",
            "Courtney Cox",
            "Jennifer Lopez",
            "Kate Winslet",
            "Emma Stone",
            "Cameron Diaz",
            "Kate Hudson",
            "Kiera Knightley",
            "Emma Watson",
            "Jennifer Lawrence",
            "Ursula Corbero",
            "Karla Souza",
            "Susan Sarandon",
            "Kelly Hu",
            "Mila Kunis",
            "Kirsten Dunst",
            "Meryl Streep",
            "Anne Hathaway",
            "Bette Davis",
            "Elizabeth Taylor",
            "Audrey Hepburn",
            "Michelle Pfeiffer",
            "Halle Berry",
            "Margot Robbie",
            "Maggie Smith",
            "Whoopi Goldberg",
            "Judy Dench",
            "Jodie Foster",
            "Julianne Moore",
            "Julianne Hough",
            "Hilary Swank",
            "Cate Blanchett",
            "Charlize Theron",
            "Diane Lane",
            "Octavia Spencer",
            "Judy Garland",
            "Julie Andrews",
            "Reese Witherspoon",
            "Jennifer Garner",
            "Sigourney Weaver",
            "Renée Zellweger",
            "Audrey Tautou",
            "Gwyneth Paltrow",
            "Liv Tyler",
            "Glenn Close",
            "Emily Blunt",
            "Jessica Alba",
            "Natalie Portman",
            "Robin Wright",
            "Emma Thompson",
            "Helena Bonham Carter",
            "Kathy Bates",
            "Diane Keaton",
            "Winona Ryder",
            "Viola Davis",
            "Cristina Ricci",
            "Mandy Moore",
            "Sarah Jessica Parker",
            "Kristen Bell",
            "Sofia Vergara",
            "Penelope Cruz",
            "Ashley Judd",
            "Salma Hayek",
            "Scarlett Johansson",
            "Amy Adams",
            "Rachel McAdams",
            "Helen Mirren",
            "Jessica Chastain",
            "Emma Roberts",
            "Zoe Saldana",
            "Sarah Paulson",
            "Elizabeth Olsen",
            "Lily Collins",
            "Rachel Weisz",
            "Amanda Seyfried",
            "Saoirse Ronan",
            "Emilia Clarke",
            "Viola Davis",
            "Elizabeth Banks",
            "Naomi Watts",
            "Jennifer Connelly",
            "Kate Beckinsale",
            "Sally Field",
            "Rosamund Pike",
            "Zendaya",
            "Blake Lively",
            "Drew Barrymore",
            "Anna Kendrick",
            "Melissa McCarthy",
            "Lupita Nyong'o",
            "Rose Byrne",
            "Anya Taylor-Joy",
            "Brie Larson",
            "Maggie Gyllenhaal",
            "Rooney Mara",
            "Claire Danes",
            "Tilda Swinton",
            "Carey Mulligan",
            "Alfre Woodard",
            "Morena Baccarin",
            "Shailene Woodley",
            "Sandra Oh",
            "Ellen Pompeo",
            "Sharon Stone",
            "Margo Martindale",
            "Kate Mara",
            "Julianna Margulies",
            "Bette Midler",
            "Krysten Ritter",
            "Noomi Rapace",
            "Mary Elizabeth Winstead",
            "Kristen Stewart",
            "Vera Farmiga",
            "Famke Janssen",
            "Tessa Thompson",
            "Priyanka Chopra",
            "Nina Dobrev",
            "Leighton Meester",
            "Alia Bhatt",
            "Sally Hawkins",
            "Taylor Schilling",
            "Jessica Lange",
            "Frances Mcdormand",
            "Jamie Lee Curtis",
            "Lindsay Lohan",
            "Shirley MacLaine",
            "Anjelica Houston",
            "Sophia Loren",
            "Carrie Fisher",
            "Sissy Spacek",
            "Catherine Zeta Jones",
            "Laura Dern",
            "Natasha Richardson",
            "Meg Ryan",
            "Eva Green",
            "Mariska Hargitay",
            "Allison Janney",
            "Dakota Fanning",
            "Jessica Biel",
            "Isla Fisher",
            "Malin Akerman",
            "Lacey Chabert",
            "Chloe Grace Moretz",
            "Olga Kurylenko",
            "Uma Thurman",
        ]

        return random.choice(actresses)
